swastik_web/apps/chatbot/urls.py
from django.urls import path
from apps.chatbot.views import ChatbotView
from apps.chatbot import views

app_name = "chatbot"

urlpatterns = [
    path("llm/", ChatbotView.as_view(), name="chatbot"),
    path("clear/", views.clear_chat, name="clear_chat"),
]

swastik_web/core/urls.py
from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path("admin/", admin.site.urls),  # Django admin route
    path("", include("apps.authentication.urls")),  # Auth routes - login / register
    # ADD NEW Routes HERE
    path("chatbot/", include("apps.chatbot.urls")),
    path("catalogue/", include("apps.quiz.urls")),
    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls")),
]

swastik_web/apps/chatbot/models.py
from django.db import models


class ChatMessage(models.Model):
    from_user = models.BooleanField()
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f'{self.timestamp} {"User" if self.from_user else "Chatbot"}: {self.text}'
        )

    @classmethod
    def clear_chat_history(cls):
        cls.objects.all().delete()

swastik_web/apps/chatbot/views.py
# Create your views here.
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.views import View
from apps.chatbot.models import ChatMessage

# from apps.chatbot.gpt_models import model
from django.shortcuts import redirect

# from chatbot import Chatbot


class ChatbotView(View):
    template_name = "chatbot/chat_window.html"

    @method_decorator(csrf_protect)
    def get(self, request):
        # Retrieve previous chat messages from the database
        messages = ChatMessage.objects.all()
        return render(request, self.template_name, {"messages": messages})

    @method_decorator(csrf_protect)
    def post(self, request):
        user_input = request.POST.get("message", "")
        chatbot_response = user_input
        # chatbot_response = model.generate("Once upon a time, ", n_predict=55, new_text_callback=new_text_callback, n_threads=8)
        # Save user input and chatbot response to the database
        ChatMessage.objects.create(from_user=True, text=user_input)
        ChatMessage.objects.create(from_user=False, text=chatbot_response)
        return redirect("chatbot:chatbot")


def clear_chat(request):
    ChatMessage.clear_chat_history()
    return redirect("chatbot:chatbot")

swastik_web/apps/templates/chatbot/chat_window.html
{% extends "layouts/base.html" %}

{% block title %} Conversational AI {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
    #chat-window {
      height: calc(100vh - 300px);
      overflow: auto;
      border: 1px solid #ccc;
      padding: 10px;
    }
    #chat-input {
      margin-top: 10px;
      width: 100%;
      height: 30px;
      border: 1px solid #ccc;
      padding: 5px;
    }
    #chat-submit {
      margin-top: 10px;
      border: none;
      background-color: #0099ff;
      color: #fff;
      padding: 5px 10px;
      cursor: pointer;
    }
    #clear-chat {
      margin-top: 10px;
      border: none;
      background-color: #cc0000;
      color: #fff;
      padding: 5px 10px;
      cursor: pointer;
    }
  </style>
{% endblock stylesheets %}

{% block content %}

<div class="container-fluid pt-3">
    <div id="chat-window">
      {% for message in messages %}
        {% if message.from_user %}
          <p><strong>{{ request.user.username }}:</strong> {{ message.text }}</p>
        {% else %}
          <p><strong>Chatbot : </strong> {{ message.text }}</p>
        {% endif %}
      {% endfor %}
    </div>
    <form method="post">
      {% csrf_token %}
      <input type="text" id="chat-input" name="message" placeholder="Type your message here">

      <button type="submit" id="chat-submit">Send</button>
      <button type="submit" id="clear-chat-btn">Clear Chat</button>
    </form>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
    // Clear chat button functionality
    $(function() {
      $('#clear-chat-btn').click(function(event) {
        event.preventDefault();
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        $.ajax({
          url: "{% url 'chatbot:clear_chat' %}",
          type: "POST",
          data: {'csrfmiddlewaretoken': csrftoken},
          success: function() {
            window.location.href = "{% url 'chatbot:chatbot' %}";
          }
        });
      });
    });
  </script>

{% endblock javascripts %}